### ISSUE TITLE
Turning off console logging

### ISSUE THREAD

**Issue by Gnindit** [pakerfeldt/node-red-contrib-envisalink#1]
Hi
Just installed Envisa link to my DSC and using it with node-red.

Is it possible to somehow turn off all the logging to the console without changing teh node.red settings to log less?

**Comment by Gnindit** [comment]
Does this code send a keep alive signal?

Poll
The TPI will respond with a Command Acknowledge code.
Note: The POLL command will also reset the Envisalink's network watchdog
timer. If there is no communications with the Envisalerts servers for a
period of 20 minutes, the Envisallink will reboot. Sending the TPI POLL
command will reset this timer. Useful if the module is not connected to the
Internet or firewalled.

**Comment by Gnindit** [comment]
Sorry, wrong repository

**Comment by pakerfeldt** [comment]
FYI, I've rebooted work on this plugin and it's now less verbose in the console output.
