### ISSUE TITLE
Keep alive signal

### ISSUE THREAD

**Issue by Gnindit** [pakerfeldt/node-red-contrib-envisalink#2]
Does this code send a keep alive signal?

From the manual
Poll
The TPI will respond with a Command Acknowledge code.
Note: The POLL command will also reset the Envisalink's network watchdog
timer. If there is no communications with the Envisalerts servers for a
period of 20 minutes, the Envisallink will reboot. Sending the TPI POLL
command will reset this timer. Useful if the module is not connected to the
Internet or firewalled.

**Comment by Gnindit** [comment]
Sorry, wrong repository

**Comment by pakerfeldt** [comment]
FYI, I recently pushed an update to reconnect to TPI should the connection fail. I'm still not actively doing `POLL` commands since I haven't seen it be necessary. But I might very well implement it in the future should it be needed.
